// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-tasks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "\u05DC\u05D0 \u05DE\u05D7\u05D5\u05D1\u05E8. \u05D9\u05E9 \u05DC\u05D4\u05EA\u05D7\u05D1\u05E8 \u05DC\u05D7\u05E9\u05D1\u05D5\u05DF Daily Dominator." }],
    isError: true
  };
}
function failure(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(text, structuredContent) {
  return { content: [{ type: "text", text }], structuredContent };
}
function todayInJerusalem() {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Jerusalem",
    year: "numeric",
    month: "2-digit",
    day: "2-digit"
  }).format(/* @__PURE__ */ new Date());
}

// src/lib/mcp/tools/list-tasks.ts
var list_tasks_default = defineTool({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's recurring tasks (name, category, time window, days of week and workout details).",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter: \u05DB\u05D5\u05E9\u05E8, \u05DC\u05D9\u05DE\u05D5\u05D3\u05D9\u05DD, \u05DB\u05E1\u05E3, \u05DE\u05E9\u05DE\u05E2\u05EA, \u05D0\u05D9\u05E9\u05D9"),
    limit: z.number().int().optional().describe("Max tasks to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("tasks").select("id,name,category,start_time,end_time,days,meaning,workout_details").order("start_time", { ascending: true }).limit(Math.min(limit ?? 50, 200));
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return ok(JSON.stringify(data ?? [], null, 2), { tasks: data ?? [] });
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a new recurring task for the signed-in user. Optionally include per-day workout details.",
  inputSchema: {
    name: z2.string().trim().min(1).describe("Task name in Hebrew."),
    category: z2.enum(["\u05DB\u05D5\u05E9\u05E8", "\u05DC\u05D9\u05DE\u05D5\u05D3\u05D9\u05DD", "\u05DB\u05E1\u05E3", "\u05DE\u05E9\u05DE\u05E2\u05EA", "\u05D0\u05D9\u05E9\u05D9"]).describe("Task category."),
    days: z2.array(z2.enum(["\u05E8\u05D0\u05E9\u05D5\u05DF", "\u05E9\u05E0\u05D9", "\u05E9\u05DC\u05D9\u05E9\u05D9", "\u05E8\u05D1\u05D9\u05E2\u05D9", "\u05D7\u05DE\u05D9\u05E9\u05D9", "\u05E9\u05D9\u05E9\u05D9", "\u05E9\u05D1\u05EA"])).describe("Days of the week the task repeats on."),
    startTime: z2.string().describe('Start time "HH:MM".'),
    endTime: z2.string().describe('End time "HH:MM".'),
    meaning: z2.string().optional().describe("Why this task matters."),
    workoutDetails: z2.array(
      z2.object({
        day: z2.string().describe("Day of week in Hebrew."),
        description: z2.string().describe('Exercises, e.g. "1. \u05DC\u05D7\u05D9\u05E6\u05EA \u05D7\u05D6\u05D4 \u2013 4x8-10, 2. ..."')
      })
    ).optional().describe("Per-day workout plan, only for \u05DB\u05D5\u05E9\u05E8 tasks.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("tasks").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      category: input.category,
      days: input.days,
      start_time: input.startTime,
      end_time: input.endTime,
      meaning: input.meaning ?? null,
      workout_details: input.workoutDetails ?? null
    }).select("id,name,category,days,start_time,end_time").single();
    if (error) return failure(error.message);
    return ok(`\u05E0\u05D5\u05E6\u05E8\u05D4 \u05DE\u05E9\u05D9\u05DE\u05D4: ${data.name}`, { task: data });
  }
});

// src/lib/mcp/tools/complete-task.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var complete_task_default = defineTool3({
  name: "complete_task",
  title: "Mark task complete",
  description: "Mark one of the signed-in user's tasks as completed (or not completed) for a given date.",
  inputSchema: {
    taskId: z3.string().uuid().describe("Task id from list_tasks."),
    date: z3.string().optional().describe('Date "YYYY-MM-DD". Defaults to today in Asia/Jerusalem.'),
    completed: z3.boolean().optional().describe("Defaults to true.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ taskId, date, completed }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const completionDate = date ?? todayInJerusalem();
    const isDone = completed ?? true;
    const { data, error } = await supabaseForUser(ctx).from("task_completions").upsert(
      {
        user_id: ctx.getUserId(),
        task_id: taskId,
        completion_date: completionDate,
        completed: isDone
      },
      { onConflict: "task_id,completion_date" }
    ).select("id,task_id,completion_date,completed").single();
    if (error) return failure(error.message);
    return ok(
      isDone ? `\u05E1\u05D5\u05DE\u05DF \u05DB\u05D4\u05D5\u05E9\u05DC\u05DD \u05DC-${completionDate}` : `\u05E1\u05D9\u05DE\u05D5\u05DF \u05D4\u05D5\u05E9\u05DC\u05DD \u05D1\u05D5\u05D8\u05DC \u05DC-${completionDate}`,
      { completion: data }
    );
  }
});

// src/lib/mcp/tools/get-progress.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_progress_default = defineTool4({
  name: "get_progress",
  title: "Get progress & streak",
  description: "Get the signed-in user's discipline stats: XP, level, current and longest streak, total completed tasks, plus recent completions.",
  inputSchema: {
    days: z4.number().int().optional().describe("How many past days of completions to include (default 7, max 90).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const window = Math.min(Math.max(days ?? 7, 1), 90);
    const since = new Date(Date.now() - window * 864e5).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    const [statsRes, completionsRes] = await Promise.all([
      supabase.from("user_stats").select("xp,level,current_streak,longest_streak,total_tasks_completed,last_active_date").eq("user_id", ctx.getUserId()).maybeSingle(),
      supabase.from("task_completions").select("task_id,completion_date,completed").gte("completion_date", since).order("completion_date", { ascending: false }).limit(500)
    ]);
    if (statsRes.error) return failure(statsRes.error.message);
    if (completionsRes.error) return failure(completionsRes.error.message);
    const payload = {
      today: todayInJerusalem(),
      stats: statsRes.data ?? null,
      windowDays: window,
      completions: completionsRes.data ?? []
    };
    return ok(JSON.stringify(payload, null, 2), payload);
  }
});

// src/lib/mcp/tools/add-journal-entry.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var add_journal_entry_default = defineTool5({
  name: "add_journal_entry",
  title: "Add reflection journal entry",
  description: "Create or update the signed-in user's daily reflection journal entry (what was learned, what was hard, what to improve, gratitude, day score).",
  inputSchema: {
    date: z5.string().optional().describe('Date "YYYY-MM-DD". Defaults to today in Asia/Jerusalem.'),
    learned: z5.string().optional().describe("What the user learned today."),
    hard: z5.string().optional().describe("What was hard today."),
    improve: z5.string().optional().describe("What to improve tomorrow."),
    grateful: z5.string().optional().describe("What the user is grateful for."),
    score: z5.number().int().optional().describe("Day score 1-10.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ date, learned, hard, improve, grateful, score }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const entryDate = date ?? todayInJerusalem();
    if (score !== void 0 && (score < 1 || score > 10)) {
      return failure("score \u05D7\u05D9\u05D9\u05D1 \u05DC\u05D4\u05D9\u05D5\u05EA \u05D1\u05D9\u05DF 1 \u05DC-10");
    }
    const { data, error } = await supabaseForUser(ctx).from("journal_entries").upsert(
      {
        user_id: ctx.getUserId(),
        entry_date: entryDate,
        learned: learned ?? null,
        hard: hard ?? null,
        improve: improve ?? null,
        grateful: grateful ?? null,
        score: score ?? null
      },
      { onConflict: "user_id,entry_date" }
    ).select("id,entry_date,score").single();
    if (error) return failure(error.message);
    return ok(`\u05E0\u05E9\u05DE\u05E8 \u05D9\u05D5\u05DE\u05DF \u05DC-${entryDate}`, { entry: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "jtdxblauyfhfvszlbppz";
var mcp_default = defineMcp({
  name: "daily-dominator-mcp",
  title: "Daily Dominator",
  version: "0.1.0",
  instructions: "Tools for Daily Dominator, a Hebrew self-discipline and fitness tracker. Use `list_tasks` to see the user's recurring tasks and workout plans, `create_task` to add one, `complete_task` to check a task off for a date, `get_progress` for XP/level/streak and recent completions, and `add_journal_entry` for the daily reflection journal. All dates are Asia/Jerusalem and all user-facing text is Hebrew.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tasks_default, create_task_default, complete_task_default, get_progress_default, add_journal_entry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
